static const char* vertex_shader_unlit_src =
    "#version 310 es\n"
    "precision highp float;\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aNormal;\n"
    "layout (location = 2) in vec2 aTexCoord;\n"
    "out vec2 TexCoord;\n"
    "layout (std140, binding = 0) uniform CameraBlock {\n"
    "   mat4 uProjection;\n"
    "   mat4 uView;\n"
    "};\n"
    "uniform mat4 uModel;\n"
    "void main() {\n"
    "   gl_Position = uProjection * uView * uModel * vec4(aPos, 1.0);\n"
    "   TexCoord = aTexCoord;\n"
    "}\n";

static const char* fragment_shader_unlit_src =
    "#version 310 es\n"
    "precision mediump float;\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D uTexture;\n"
    "void main() {\n"
    "   FragColor = texture(uTexture, TexCoord);\n"
    "}\n";

static const char* vertex_shader_lit_src =
    "#version 310 es\n"
    "precision highp float;\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aNormal;\n"
    "layout (location = 2) in vec2 aTexCoord;\n"
    "out vec3 FragPos;\n"
    "out vec3 Normal;\n"
    "out vec2 TexCoord;\n"
    "layout (std140, binding = 0) uniform CameraBlock {\n"
    "   mat4 uProjection;\n"
    "   mat4 uView;\n"
    "};\n"
    "uniform mat4 uModel;\n"
    "void main() {\n"
    "   FragPos = vec3(uModel * vec4(aPos, 1.0));\n"
    "   Normal = mat3(transpose(inverse(uModel))) * aNormal;\n"
    "   TexCoord = aTexCoord;\n"
    "   gl_Position = uProjection * uView * vec4(FragPos, 1.0);\n"
    "}\n";

static const char* vertex_shader_skeleton_lit_src =
    "#version 310 es\n"
    "precision highp float;\n"
    "layout(location = 0) in vec3 aPos;\n"
    "layout(location = 1) in vec3 aNormal;\n"
    "layout(location = 2) in vec2 aTexCoord;\n"
    "layout(location = 3) in vec4 aWeights;\n"
    "layout(location = 4) in ivec4 aBoneIds;\n" /* Transmis depuis GL_BYTE */
    "layout (std140, binding = 0) uniform CameraBlock {\n"
    "   mat4 uProjection;\n"
    "   mat4 uView;\n"
    "};\n"
    "layout (std140, binding = 1) uniform BonesBlock {\n"
    "   mat4 finalBonesMatrices[100];\n"
    "};\n"
    "uniform mat4 uModel;\n"
    "out vec3 FragPos;\n"
    "out vec3 Normal;\n"
    "out vec2 TexCoord;\n"
    "void main()\n"
    "{\n"
    "    vec4 totalPosition = vec4(0.0);\n"
    "    vec3 totalNormal = vec3(0.0);\n"
    "    int bonesApplied = 0;\n"
    "    for(int i = 0 ; i < 4 ; i++)\n"
    "    {\n"
    "        if(aBoneIds[i] == -1)\n"
    "            continue;\n"
    "        if(aBoneIds[i] >= 100)\n"
    "        {\n"
    "            totalPosition = vec4(aPos, 1.0);\n"
    "            totalNormal = aNormal;\n"
    "            bonesApplied++;\n"
    "            break;\n"
    "        }\n"
    "        vec4 localPosition = finalBonesMatrices[aBoneIds[i]] * vec4(aPos, 1.0);\n"
    "        totalPosition += localPosition * aWeights[i];\n"
    "        vec3 localNormal = mat3(finalBonesMatrices[aBoneIds[i]]) * aNormal;\n"
    "        totalNormal += localNormal * aWeights[i];\n"
    "        bonesApplied++;\n"
    "    }\n"
    "    if (bonesApplied == 0 || totalPosition.w == 0.0) {\n"
    "        totalPosition = vec4(aPos, 1.0);\n"
    "        totalNormal = aNormal;\n"
    "    }\n"
    "    FragPos = vec3(uModel * totalPosition);\n"
    "    Normal = mat3(transpose(inverse(uModel))) * totalNormal;\n"
    "    TexCoord = aTexCoord;\n"
    "    gl_Position = uProjection * uView * vec4(FragPos, 1.0);\n"
    "}\n";

static const char* fragment_shader_lit_src =
    "#version 310 es\n"
    "precision mediump float;\n"
    "in vec3 FragPos;\n"
    "in vec3 Normal;\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "struct Material {\n"
    "    sampler2D texture_diffuse;\n"
    "    float shininess;\n"
    "};\n"
    "struct Light {\n"
    "    int type;\n"
    "    vec3 position;\n"
    "    vec3 direction;\n"
    "    vec3 color;\n"
    "    float intensity;\n"
    "    float range;\n"
    "};\n"
    "#define MAX_LIGHTS 4\n"
    "uniform Material uMaterial;\n"
    "uniform Light uLights[MAX_LIGHTS];\n"
    "uniform vec3 uAmbientLight;\n"
    "uniform vec3 uViewPos;\n"
    "void main() {\n"
    "   vec4 texColor = texture(uMaterial.texture_diffuse, TexCoord);\n"
    "   vec3 ambient = uAmbientLight * texColor.rgb;\n"
    "   vec3 norm = normalize(Normal);\n"
    "   vec3 viewDir = normalize(uViewPos - FragPos);\n"
    "   vec3 diffuseAccum = vec3(0.0);\n"
    "   for (int i = 0; i < MAX_LIGHTS; ++i) {\n"
    "       if (uLights[i].intensity <= 0.0) continue;\n"
    "       vec3 lightDir;\n"
    "       float attenuation = 1.0;\n"
    "       if (uLights[i].type == 0) {\n"
    "           lightDir = normalize(-uLights[i].direction);\n"
    "       } else {\n"
    "           vec3 lightVec = uLights[i].position - FragPos;\n"
    "           float distance = length(lightVec);\n"
    "           lightDir = normalize(lightVec);\n"
    "           if (uLights[i].range > 0.0) {\n"
    "               float ratio = distance / uLights[i].range;\n"
    "               attenuation = 1.0 / (1.0 + 2.0 * ratio + ratio * ratio);\n"
    "               if (distance > uLights[i].range) attenuation = 0.0;\n"
    "           }\n"
    "       }\n"
    "       float diff = max(dot(norm, lightDir), 0.0);\n"
    "       diffuseAccum += uLights[i].color * uLights[i].intensity * diff * texColor.rgb * attenuation;\n"
    "   }\n"
    "   vec3 result = ambient + diffuseAccum;\n"
    "   FragColor = vec4(result, texColor.a);\n"
    "}\n";